a=int(input('Enter A:-'))
b=int(input('Enter B:-'))
print('_______________________')
print('sum=')
print(a+b)
print('_______________________')
print('diff(a-b)=')
print(a-b)
print('_______________________')
print('diff(b-a)=')
print(b-a)
print('_______________________')
print('product=')
print(a*b)
print('_______________________')
print('div(a/b)=')
print(a/b)
print('_______________________')
print('div(b/a)=')
print(b/a)
print('________________________')
print('a power of b=')
print(a**b)
print('________________________')
print('b power of a=')
print(b**a)
print('_________________________')
